# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: TransforMate Bot Docs
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
nav:
  - Home: index.md
  - Tutorials:
      - Summary: tutorials/summary.md
      - Basic TransforMate Tutorial: tutorials/basic.md
      - Basic Twinning Tutorial: tutorials/twinning.md
  - Commands:
      - Summary: commands/summary.md
      - Transformation:
          - Index: commands/transformation/index.md
          - /transform: commands/transformation/transform.md
          - /goback: commands/transformation/goback.md
      - Set and Clear:
          - Index: commands/set_and_clear/index.md
      - Get:
          - Index: commands/get/index.md
      - Block:
          - Index: commands/block/index.md
      - Admin:
          - Index: commands/admin/index.md
      - Others:
          - Index: commands/others/index.md
  - About: about.md
plugins:
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format