# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: TransforMate Bot Docs
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
nav:
  - Home: index.md
  - Commands:
      - Summary: commands/summary.md
      - Transformation:
          - Index: commands/transformation/index.md
      - Set:
          - Index: commands/set/index.md
      - Clear:
          - Index: commands/clear/index.md
      - Get:
          - Index: commands/clear/index.md
      - Block:
          - Index: commands/block/index.md
      - Admin:
          - Index: commands/admin/index.md
      - Others:
          - Index: commands/others/index.md
  - About: about.md
plugins:
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences